const {readFileSync}=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const data=JSON.parse(readFileSync('docs/data/content.json'));
const nodes=new Map();function mockElement(){return {value:'',textContent:'',innerHTML:'',hidden:false,isConnected:true,dataset:{},previousElementSibling:null,firstElementChild:null,querySelectorAll:()=>[],insertAdjacentHTML(pos,html){this.innerHTML=pos==='beforeend'?this.innerHTML+html:html+this.innerHTML},replaceWith(el){this.replacedWith=el},remove(){this.removed=true}}}function node(s){if(!nodes.has(s))nodes.set(s,mockElement());return nodes.get(s)}
const documentMock={querySelector:node,getElementById:id=>node('#'+id),querySelectorAll:()=>[],createElement:()=>mockElement()};
const ctx=vm.createContext({URL,console,setTimeout,clearTimeout,AbortController,document:documentMock,window:{addEventListener(){}},navigator:{},localStorage:{getItem:()=>null}});
for(const file of ['app.js','assistants.js','resenha-dependent.js','resenha-admin-aggravants.js','resenha-aia-penal.js','resenha-nature-other.js','resenha-ui-fix.js','technical.js','router-patch.js'])vm.runInContext(readFileSync('docs/'+file,'utf8').replace(/^boot\(\);$/m,''),ctx);
const run=s=>vm.runInContext(s,ctx);run('DATA='+JSON.stringify(data));
run("navigate('reurb')");assert.match(node('#content').innerHTML,/CRF/);assert.match(node('#content').innerHTML,/Validar Responsável/);
run("navigate('technical')");assert.match(node('#matrixOut').innerHTML,/Inventário florestal/);
run("renderMatrix('georreferenciamento')");assert.match(node('#matrixOut').innerHTML,/Topografia/);assert.doesNotMatch(node('#matrixOut').innerHTML,/Inventário florestal/);
const valid={object:'Inventário',name:'Teste fictício',profession:'Outra profissão',council:'Conselho',registration:'123',responsibility:'Documento 1',proof:'Certidão específica fictícia',register:'yes',attribution:'yes',scope:'yes'};
function verdict(v){return run('technicalVerdict('+JSON.stringify(v)+').color')}
assert.equal(verdict({}),'gray');assert.equal(verdict({...valid,proof:''}),'yellow');assert.equal(verdict(valid),'green');assert.equal(verdict({...valid,attribution:'no'}),'red');assert.equal(verdict({...valid,scope:'no',proof:''}),'yellow');assert.equal(verdict({...valid,registration:' '}),'gray');
for(const q of ['APP','CRF','ART','inventário florestal','Reurb'])assert.ok(run('localEvidence('+JSON.stringify(q)+').length')>0,q);
run("navigate('assistant')");node('#occInput').value='Apresentou autorização da Prefeitura para Reurb junto a córrego.';
(async()=>{await run("submitAssistant('occurrence','occInput')");for(const term of ['ELEMENTOS A CONFIRMAR','ROTEIRO DE VERIFICAÇÃO','CONDICIONADAS'])assert.ok(node('#occInputOut').innerHTML.includes(term),term);
run("navigate('resenha')");const resenhaHtml=node('#content').innerHTML+node('#reportAuthors').innerHTML+run('aaForwardSelect()');for(const term of ['Gerador de Resenha Policial','Nº do BOPAmb','repBOPAmb','Natureza da ocorrência','<select id="repNature"','Fauna','Flora','Pesca','Poluição','Outra','Outra natureza','Digite a natureza da ocorrência','Município','Constatação / fatos objetivos','Autores e autuações','Adicionar autor','Autos de Infração Ambiental deste autor','Adicionar AIA','Enquadramento administrativo deste AIA','Enquadramento penal deste AIA','Agravante / majoração administrativa','Agravante/majoração aplicada','AIA anterior','Penalidade aplicada','Medidas administrativas gerais','Atendimento Ambiental','Data do Atendimento Ambiental','Hora do Atendimento Ambiental','Forma de encaminhamento','Resolução SIMA nº 05/2021','Código Penal — Decreto-Lei nº 2.848/1940','Distrito Policial'])assert.ok(resenhaHtml.includes(term),term);
const aiaHtml=run('aiaBlock(1,1)');for(const term of ['repAuthor1Aia1Number','repAuthor1Aia1AdminNorm','repAuthor1Aia1AdminArticle','repAuthor1Aia1PenalNorm','repAuthor1Aia1PenalArticle','Enquadramento penal deste AIA'])assert.ok(aiaHtml.includes(term),term);const aia2Html=run('aiaBlock(1,2)');assert.ok(aia2Html.includes('repAuthor1Aia2PenalArticle'),'segundo AIA deve ter enquadramento penal próprio');assert.notEqual(run("'repAuthor1Aia1PenalArticle'"),run("'repAuthor1Aia2PenalArticle'"));
assert.ok(!/<input id="repNature" type="text"/i.test(node('#content').innerHTML),'Natureza da ocorrência não pode permanecer como campo de texto simples');
const aggravants=run('JSON.stringify(RESENHA_ADMIN_AGGRAVANTS)').toLowerCase();for(const term of ['mesma infração ambiental: multa em triplo','infração ambiental distinta: multa em dobro','vantagem pecuniária','unidade de conservação','período de defeso','métodos cruéis','mediante fraude','espécie ameaçada','funcionário público','à noite','domingo ou feriado'])assert.ok(aggravants.includes(term),term);
const penalMap=run('JSON.stringify(RESENHA_PENAL_BY_NORM)');for(const term of ['Art. 29, § 1º, III','Art. 32, § 1º-C','Art. 34, parágrafo único, III','Art. 38-A','Art. 46, parágrafo único','Art. 53, II, e','Art. 54, § 2º, V','Art. 56, § 1º, II','Art. 60, parágrafo único','Art. 69-A, § 2º','Art. 180','Art. 261','Art. 330','Outro — informar artigo/dispositivo'])assert.ok(penalMap.includes(term),term);
assert.ok(!resenhaHtml.includes('Medidas vinculadas a este autor'),'medidas vinculadas ao autor não devem aparecer');assert.ok(!resenhaHtml.includes('Providências na esfera penal'),'campo penal antigo não deve aparecer');
for(const [id,value] of [['repBOPAmb','12345'],['repBattalion','1º Batalhão de Polícia Ambiental'],['repCompany','1ª Companhia de Polícia Ambiental'],['repPlatoon','1º Pelotão de Polícia Ambiental'],['repNature','Flora'],['repDate','2026-09-14'],['repTime','08:30'],['repCity','São Paulo'],['repPlace','Local de teste'],['repFacts','Constatação objetiva para teste automatizado.']])node('#'+id).value=value;
run('generateResenha()');assert.match(node('#reportOut').textContent,/\\*Comando de Policiamento Ambiental\\*/);assert.match(node('#reportOut').textContent,/\\*BOPAmb nº:\\* 12345/);assert.match(node('#reportOut').textContent,/1º Batalhão de Polícia Ambiental/);assert.match(node('#reportOut').textContent,/1ª Companhia de Polícia Ambiental/);assert.match(node('#reportOut').textContent,/1º Pelotão de Polícia Ambiental/);assert.match(node('#reportOut').textContent,/14\/09\/2026/);assert.match(node('#reportOut').textContent,/08:30 h/);assert.match(node('#reportOut').textContent,/\\*Município:\\* São Paulo/);assert.match(node('#reportOut').textContent,/Rascunho gerado para revisão/);assert.match(node('#reportStatus').textContent,/Ocorrência gerada/);
node('#repNature').value='Outra';node('#repNatureOther').value='Intervenção ambiental diversa';run('generateResenha()');assert.match(node('#reportOut').textContent,/Comando de Policiamento Ambiental/);
const sampleAia=run("whatsappAiaText({label:'AIA 1',number:'11222-1',adminNorm:'Resolução SIMA nº 05/2021',adminArticle:'Art. 25',penalties:['Multa simples','Apreensão'],value:'1000',penalNorm:'Lei Federal nº 9.605/1998',penalArticle:'Art. 29'})");for(const term of ['*AIA 1 nº 11222-1*','*Enquadramento administrativo:*','*Norma:*','*Fundamento:*','*Penalidade:*','*Enquadramento penal:*'])assert.ok(sampleAia.includes(term),term);assert.equal(run("whatsappAuthorLabel({name:'AD 1'},0)"),'Autor Direto 1');assert.equal(run("whatsappAuthorLabel({name:'AI 1'},0)"),'Autor Indireto 1');
const sw=readFileSync('docs/sw.js','utf8'),html=readFileSync('docs/index.html','utf8');for(const [,asset] of html.matchAll(/<script src="([^"]+)"/g))assert.ok(sw.includes("'"+asset+"'"),asset+' ausente no cache');
console.log('OK: REURB, matriz, busca, ocorrência, BOPAmb, múltiplos AIAs por autor com enquadramento penal individual, geração funcional, natureza selecionável, agravantes, Lei 9.605/98, Código Penal, encaminhamentos e cache.');})().catch(e=>{console.error(e);process.exitCode=1});
