const {readFileSync}=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const data=JSON.parse(readFileSync('docs/data/content.json'));
const nodes=new Map();function node(s){if(!nodes.has(s))nodes.set(s,{value:'',textContent:'',innerHTML:'',isConnected:true,querySelectorAll:()=>[],insertAdjacentHTML(_,s){this.innerHTML=s+this.innerHTML}});return nodes.get(s)}
const ctx=vm.createContext({URL,console,setTimeout,clearTimeout,AbortController,document:{querySelector:node,getElementById:id=>node('#'+id),querySelectorAll:()=>[]},window:{addEventListener(){}},navigator:{},localStorage:{getItem:()=>null}});
for(const file of ['app.js','assistants.js','resenha-dependent.js','technical.js','router-patch.js'])vm.runInContext(readFileSync('docs/'+file,'utf8').replace(/^boot\(\);$/m,''),ctx);
const run=s=>vm.runInContext(s,ctx);run('DATA='+JSON.stringify(data));
run("navigate('reurb')");assert.match(node('#content').innerHTML,/CRF/);assert.match(node('#content').innerHTML,/Validar Responsável/);
run("navigate('technical')");assert.match(node('#matrixOut').innerHTML,/Inventário florestal/);
run("renderMatrix('georreferenciamento')");assert.match(node('#matrixOut').innerHTML,/Topografia/);assert.doesNotMatch(node('#matrixOut').innerHTML,/Inventário florestal/);
const valid={object:'Inventário',name:'Teste fictício',profession:'Outra profissão',council:'Conselho',registration:'123',responsibility:'Documento 1',proof:'Certidão específica fictícia',register:'yes',attribution:'yes',scope:'yes'};
function verdict(v){return run('technicalVerdict('+JSON.stringify(v)+').color')}
assert.equal(verdict({}),'gray');assert.equal(verdict({...valid,proof:''}),'yellow');assert.equal(verdict(valid),'green');assert.equal(verdict({...valid,attribution:'no'}),'red');assert.equal(verdict({...valid,scope:'no',proof:''}),'yellow');assert.equal(verdict({...valid,registration:' '}),'gray');
for(const q of ['APP','CRF','ART','inventário florestal','Reurb'])assert.ok(run('localEvidence('+JSON.stringify(q)+').length')>0,q);
run("navigate('assistant')");node('#occInput').value='Apresentou autorização da Prefeitura para Reurb junto a córrego.';
(async()=>{await run("submitAssistant('occurrence','occInput')");for(const term of ['ELEMENTOS A CONFIRMAR','ROTEIRO DE VERIFICAÇÃO','CONDICIONADAS'])assert.ok(node('#occInputOut').innerHTML.includes(term),term);
run("navigate('resenha')");const resenhaHtml=node('#content').innerHTML;for(const term of ['Gerador de Resenha Policial','Natureza da ocorrência','Município','Constatação / fatos objetivos','Autores e autuações','Adicionar autor','Enquadramento administrativo','Enquadramento penal','Penalidade aplicada','Medidas administrativas gerais','Atendimento Ambiental','Data do Atendimento Ambiental','Hora do Atendimento Ambiental','Forma de encaminhamento','Resolução SIMA nº 05/2021'])assert.ok(resenhaHtml.includes(term),term);assert.ok(!resenhaHtml.includes('Medidas vinculadas a este autor'),'medidas vinculadas ao autor não devem aparecer');assert.ok(!resenhaHtml.includes('Providências na esfera penal'),'campo penal antigo não deve aparecer');
for(const [id,value] of [['repNature','Flora'],['repDate','2026-09-14'],['repTime','08:30'],['repCity','São Paulo'],['repPlace','Local de teste'],['repFacts','Constatação objetiva para teste automatizado.']])node('#'+id).value=value;
run('generateResenha()');assert.match(node('#reportOut').textContent,/RESENHA POLICIAL/);assert.match(node('#reportOut').textContent,/14\/09\/2026/);assert.match(node('#reportOut').textContent,/08:30 h/);assert.match(node('#reportOut').textContent,/São Paulo/);assert.match(node('#reportOut').textContent,/Rascunho gerado para revisão/);
const sw=readFileSync('docs/sw.js','utf8'),html=readFileSync('docs/index.html','utf8');for(const [,asset] of html.matchAll(/<script src="([^"]+)"/g))assert.ok(sw.includes("'"+asset+"'"),asset+' ausente no cache');
console.log('OK: REURB, matriz, busca, ocorrência, resenha SIMA 05/2021, caixas prontas, múltiplas penalidades, atendimento ambiental e cache.');})().catch(e=>{console.error(e);process.exitCode=1});
