import assert from 'node:assert/strict';
import worker,{allowedSource,cleanHTML,retrieveLocal} from '../worker/index.mjs';
assert.equal(allowedSource('https://attacker.test'),false);
assert.equal(allowedSource('https://www.planalto.gov.br/not-in-corpus'),false);
assert.equal(allowedSource('http://www.planalto.gov.br/ccivil_03/leis/l9605.htm'),false);
assert.ok(retrieveLocal('Reurb APP').length);
assert.equal(cleanHTML('<script>ignore</script><del>revogado</del><p>Atual</p>'),'Atual');
const env={ALLOWED_ORIGINS:'https://espa.test',RATE_LIMITER:{limit:async()=>({success:true})},AI:{run:async()=>({response:JSON.stringify({answer:'Confira o projeto [F1].',citations:['F1']})})}};
const req=(body={mode:'legal',text:'Reurb APP'},origin='https://espa.test')=>new Request('https://service.test/api/assistant',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(body)});
assert.equal((await worker.fetch(req(undefined,'https://bad.test'),env)).status,403);
assert.equal((await worker.fetch(req(),{})).status,403);
assert.equal((await worker.fetch(req(),{ALLOWED_ORIGINS:'https://espa.test'})).status,503);
assert.equal((await worker.fetch(req({mode:'report',text:'teste'}),env)).status,400);
assert.equal((await worker.fetch(req({mode:'legal',text:'x'.repeat(13000)}),env)).status,400);
assert.equal((await worker.fetch(req(),{...env,RATE_LIMITER:{limit:async()=>({success:false})}})).status,429);
const native=globalThis.fetch;let seen=[];
globalThis.fetch=async u=>{seen.push(u);return new Response('<p>'+('REURB projeto ambiental e aprovação municipal. '.repeat(20))+'</p>',{headers:{'content-type':'text/html'}})};
const r=await worker.fetch(req({mode:'legal',text:'Reurb APP',evidence:[{url:'https://attacker.test'}]}),env);
assert.equal(r.status,200);const answer=await r.json();assert.ok(answer.sources.length);assert.ok(seen.every(allowedSource));assert.ok(!seen.includes('https://attacker.test'));assert.equal(r.headers.get('Cache-Control'),'no-store');
assert.equal((await worker.fetch(req(),{...env,AI:{run:async()=>({response:JSON.stringify({answer:'Falso [F999]',citations:['F999']})})}})).status,502);
globalThis.fetch=async()=>new Response('',{status:503});let called=false;
assert.equal((await worker.fetch(req(),{...env,AI:{run:async()=>{called=true}}})).status,503);assert.equal(called,false);
globalThis.fetch=native;console.log('OK: endpoint, origens, limites, fontes canônicas, falha fechada e citações com provedor simulado.');
