const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../docs'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const data=JSON.parse(read('data/content.json'));
const nodes=new Map(),node=s=>{if(!nodes.has(s))nodes.set(s,{value:'',textContent:'',innerHTML:'',querySelectorAll:()=>[],showModal(){this.open=true},addEventListener(){}});return nodes.get(s)};
const saved=new Map();
const context=vm.createContext({URL,document:{querySelector:node},window:{addEventListener(){}},navigator:{},localStorage:{getItem:k=>saved.get(k),setItem:(k,v)=>saved.set(k,v)},console});
const app=read('app.js');
for(const file of ['app.js','reader.js','sw.js'])new vm.Script(read(file),{filename:file});
vm.runInContext(app.replace(/^boot\(\);$/m,''),context);
vm.runInContext('DATA='+JSON.stringify(data),context);
const run=s=>vm.runInContext(s,context),set=(id,value)=>node(id).value=String(value);
assert.equal(data.modules.length,9);
assert.equal(data.modules.flatMap(m=>m.items).length,45);
assert.equal(data.modules.find(m=>m.id==='referencia').items.length,30);
assert.equal(data.nexo_causal.criteria.length,8);
run('renderHome()');assert.match(node('#content').innerHTML,/role="button" tabindex="0"/);
run("renderSearch('poluicao')");assert.doesNotMatch(node('#content').innerHTML,/Nenhum resultado/);
run("renderModule('flora');toggleFav(allItems()[0].title)");assert.equal(run('currentView'),'module:flora');
saved.set('favs','{broken');assert.equal(run('favs().length'),1); // recover session copy
assert.equal(run("esc('<script>')"),'&lt;script&gt;');
for(const [input,expected] of [['',/maior que zero/],[-1,/maior que zero/],[9,/30 m/],[10,/50 m/],[50,/limite/],[200,/limite/],[600,/200 m/],[601,/500 m/]]){set('#river',input);run('calcAPP()');assert.match(node('#appOut').textContent,expected)}
set('#len',100);set('#wid',100);run('calcArea()');assert.match(node('#areaOut').textContent,/1.0000 ha/);
set('#len','');run('calcArea()');assert.match(node('#areaOut').textContent,/maiores que zero/);
set('#deg',23);set('#min',30);set('#sec',0);set('#hem','S');run('calcCoord()');assert.equal(node('#coordOut').textContent,'-23.5000000');
set('#min',60);run('calcCoord()');assert.match(node('#coordOut').textContent,/Confira/);
set('#deg',90);set('#min',1);run('calcCoord()');assert.match(node('#coordOut').textContent,/Confira/);
set('#min',0);run('calcCoord()');assert.equal(node('#coordOut').textContent,'-90.0000000');
run('genBop()');assert.match(node('#bopOut').textContent,/\[DATA\]/);
run('genNexo()');for(const c of data.nexo_causal.criteria)assert.ok(node('#nxout').textContent.includes('Critério '+c.n+' –'));
vm.runInContext(read('reader.js').split('const reader=')[0],context);
for(const item of data.modules.flatMap(m=>m.items))for(const d of item.documents||[]){assert.ok(run('safeSource('+JSON.stringify(d.url)+')'),d.url);assert.ok(d.title)}
for(const url of ['javascript:alert(1)','https://gov.br.attacker.test/x','http://www.planalto.gov.br/','https://a@www.planalto.gov.br/'])assert.equal(run('safeSource('+JSON.stringify(url)+')'),null);
const handlers={},cacheMock={open:async()=>({match:async()=> 'cached'}),keys:async()=>['pamb-old','pamb-v2.1.0','unrelated'],delete:async k=>{assert.equal(k,'pamb-old')}};
vm.runInNewContext(read('sw.js'),{URL,caches:cacheMock,self:{addEventListener:(event,fn)=>handlers[event]=fn,location:{origin:'https://example.test'},registration:{scope:'https://example.test/app/'},clients:{claim:async()=>{}}}});
let called=false;handlers.fetch({request:{url:'https://www.planalto.gov.br/',method:'GET'},respondWith(){called=true}});assert.equal(called,false);
handlers.fetch({request:{url:'https://example.test/other/',method:'GET'},respondWith(){called=true}});assert.equal(called,false);
handlers.fetch({request:{url:'https://example.test/app/',method:'GET',mode:'navigate'},respondWith(p){called=true;p.then(v=>assert.equal(v,'cached'))}});assert.equal(called,true);
for(const asset of ['index.html','styles.css','app.js','reader.js','manifest.webmanifest','data/content.json'])assert.ok(fs.existsSync(path.join(root,asset)));
JSON.parse(read('manifest.webmanifest'));
const readerNodes=new Map(),elements=[];
const element=()=>({children:[],dataset:{},textContent:'',setAttribute(){},appendChild(e){this.children.push(e)},replaceChildren(){this.children=[]},addEventListener(t,f){this[t]=f},showModal(){this.open=true},close(){this.open=false}});
const readerNode=s=>{if(!readerNodes.has(s))readerNodes.set(s,element());return readerNodes.get(s)};
const readerContext=vm.createContext({URL,navigator:{onLine:true},document:{createElement(){const e=element();elements.push(e);return e},querySelector:readerNode,body:element(),addEventListener(){}}});
vm.runInContext(read('reader.js'),readerContext);
vm.runInContext("openDocument('https://www.planalto.gov.br/ccivil_03/leis/l9605.htm','Lei 9.605')",readerContext);
assert.equal(readerNode('#readerFrame').children[0].title,'Lei 9.605');assert.equal(elements[0].open,true);
assert.equal(readerNode('#readerExternal').href,'https://www.planalto.gov.br/ccivil_03/leis/l9605.htm');
readerContext.navigator.onLine=false;vm.runInContext("openDocument('https://www.planalto.gov.br/','Offline')",readerContext);
assert.equal(readerNode('#readerFrame').children.length,0);assert.match(readerNode('#readerFrame').innerHTML,/precisa de conexão/);
console.log('OK: conteúdo V2, navegação, favoritos, cálculos, relatórios, fontes permitidas e isolamento do cache.');
