import corpus from '../docs/data/content.json' with { type: 'json' };
import { runFreeAI } from './providers.mjs';
import { authenticate, authorize } from './auth.mjs';
import { platformApi } from './platform-api.mjs';
const normalize=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const items=corpus.modules.flatMap(m=>m.items);const approved=new Set(items.flatMap(i=>(i.documents||[]).map(d=>d.url)));
export function allowedSource(raw){try{const u=new URL(raw);return u.protocol==='https:'&&!u.username&&!u.password&&approved.has(u.href)}catch{return false}}
export function retrieveLocal(text){const tokens=normalize(text).split(/[^a-z0-9]+/).filter(t=>t.length>2&&!['que','para','como','qual','pode','com','uma'].includes(t));return items.map(i=>({i,n:tokens.reduce((n,t)=>n+Number(normalize([i.title,i.summary,...i.tags||[]].join(' ')).includes(t)),0)})).filter(x=>x.n>0).sort((a,b)=>b.n-a.n).slice(0,6).map(x=>x.i)}
async function limitedBytes(response,max){if(!response.body)throw Error('empty');const reader=response.body.getReader();const parts=[];let size=0;try{while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>max)throw Error('size');parts.push(value)}}finally{await reader.cancel().catch(()=>{})}const bytes=new Uint8Array(size);let offset=0;for(const part of parts){bytes.set(part,offset);offset+=part.length}return bytes}
export function cleanHTML(html){return html.replace(/<(script|style|nav|header|footer|del|s|strike)\b[^>]*>[\s\S]*?<\/\1>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/\s+/g,' ').trim()}
function excerpts(text,query){const tokens=normalize(query).split(/[^a-z0-9]+/).filter(t=>t.length>3),lower=normalize(text),starts=[0,...tokens.map(t=>lower.indexOf(t)).filter(n=>n>=0).map(n=>Math.max(0,n-350))];return [...new Set(starts)].slice(0,5).map(n=>text.slice(n,n+1500)).join('\n[…]\n').slice(0,6000)}
async function officialText(d,query){const base={title:d.title,url:d.url,retrievedAt:new Date().toISOString()};try{if(!allowedSource(d.url))throw Error();const r=await fetch(d.url,{redirect:'error',signal:AbortSignal.timeout(7000),headers:{Accept:'text/html,text/plain'}});if(!r.ok)throw Error();const type=r.headers.get('content-type')||'';if(!/text\/(html|plain)/i.test(type))return {...base,status:'Texto não extraído (PDF ou formato não suportado)',text:''};const raw=new TextDecoder().decode(await limitedBytes(r,900000)),cleaned=cleanHTML(raw);if(cleaned.length<200)throw Error();return {...base,status:'Trechos recuperados; vigência exige conferência',text:excerpts(cleaned,query)}}catch{return {...base,status:'Fonte indisponível; consulta não confirmada',text:''}}}
export const SYSTEM=`Você é o assistente de apoio da ESPA. Responda em português brasileiro. Use SOMENTE o corpus interno e os trechos oficiais fornecidos. Não invente fatos, artigos, competência, responsabilidade, autorização ou procedimento. Diferencie relato, norma, hipótese e lacuna. Não conclua quando faltarem elementos. Citações [F1] etc devem sustentar as afirmações. Retorne exclusivamente JSON: {"answer":"texto com citações [F1] etc","citations":["F1"]}.`;
export default {async fetch(request,env){const origin=request.headers.get('Origin'),allowed=(env.ALLOWED_ORIGINS||'').split(',').map(s=>s.trim()).filter(Boolean),headers={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Vary':'Origin','X-Content-Type-Options':'nosniff'},reply=(body,status=200)=>new Response(JSON.stringify(body),{status,headers});if(!origin||!allowed.includes(origin))return reply({error:'Origem não autorizada'},403);headers['Access-Control-Allow-Origin']=origin;if(request.method==='OPTIONS'){headers['Access-Control-Allow-Methods']='GET, POST, OPTIONS';headers['Access-Control-Allow-Headers']='Content-Type, Authorization';return new Response(null,{status:204,headers})}const path=new URL(request.url).pathname;if(path.startsWith('/api/courses')||path.startsWith('/api/enrollments')||path==='/api/audit')return platformApi(request,env,{'Access-Control-Allow-Origin':origin,'Vary':'Origin','X-Content-Type-Options':'nosniff'});if(path!=='/api/assistant')return reply({error:'Não encontrado'},404);if(request.method!=='POST')return reply({error:'Método não permitido'},405);let identity;try{identity=await authenticate(request,env)}catch{return reply({error:'Autenticação necessária'},401)}if(!authorize(identity))return reply({error:'Acesso não autorizado'},403);if(!env.RATE_LIMITER)return reply({error:'Serviço não ativado'},503);try{if(!(await env.RATE_LIMITER.limit({key:identity.subject})).success)return reply({error:'Limite de consultas atingido'},429);const body=JSON.parse(new TextDecoder().decode(await limitedBytes(request,50000)));if(!['legal','occurrence'].includes(body.mode)||typeof body.text!=='string'||!body.text.trim()||body.text.length>12000)return reply({error:'Modo ou texto inválido'},400);const local=retrieveLocal(body.text),docs=[...new Map(local.flatMap(i=>i.documents||[]).map(d=>[d.url,d])).values()].filter(d=>allowedSource(d.url)).slice(0,5),official=await Promise.all(docs.map(d=>officialText(d,body.text))),usable=official.filter(s=>s.text).map((s,n)=>({...s,id:'F'+(n+1)}));if(!usable.length)return reply({error:'Não foi possível recuperar texto oficial para fundamentar a resposta'},503);const generated=await runFreeAI(env,SYSTEM,{mode:body.mode,relato:body.text,biblioteca:local,trechos:usable}),parsed=JSON.parse(generated.text.replace(/^```(?:json)?\s*|\s*```$/g,'')),ids=new Set(usable.map(s=>s.id)),inline=[...String(parsed.answer||'').matchAll(/\[(F\d+)\]/g)].map(m=>m[1]);if(!parsed.answer||!Array.isArray(parsed.citations)||!parsed.citations.length||!inline.length||!parsed.citations.every(x=>ids.has(x)&&inline.includes(x)))return reply({error:'Resposta sem referências válidas'},502);return reply({answer:parsed.answer,provider:generated.provider,sources:usable.filter(s=>parsed.citations.includes(s.id)).map(({text,...s})=>({...s,title:'['+s.id+'] '+s.title}))})}catch{return reply({error:'IA temporariamente indisponível; use o roteiro local e tente novamente mais tarde.'},503)}}};
