import {authenticate,authorize} from './auth.mjs';
import {assertJson,rateLimit,rejectUnsafeQuery} from './security.mjs';
const json=(body,status=200,headers={})=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers}});
const parse=async r=>{assertJson(r);const t=await r.text();if(t.length>30000)throw Object.assign(Error('too-large'),{status:413});return JSON.parse(t||'{}')};
const id=()=>crypto.randomUUID(),text=(v,max=4000)=>String(v??'').trim().slice(0,max),date=v=>/^\d{4}-\d{2}-\d{2}$/.test(String(v||''))?String(v):'',statuses=new Set(['draft','published','cancelled','archived']);
async function audit(db,user,action,type,target){await db.prepare('INSERT INTO audit_log(at,actor_subject,action,target_type,target_id) VALUES(?,?,?,?,?)').bind(new Date().toISOString(),user.subject,action,type,target).run()}
export async function platformApi(request,env,cors){try{rejectUnsafeQuery(request);if(!env.DB)return json({error:'Banco de dados não configurado'},503,cors);const url=new URL(request.url),p=url.pathname,user=await authenticate(request,env).catch(()=>null);
 if(p==='/api/courses'&&request.method==='GET'){const year=Number(url.searchParams.get('year'))||new Date().getFullYear();if(year<2020||year>2100)return json({error:'Ano inválido'},400,cors);const rows=await env.DB.prepare("SELECT id,year,title,audience,location,start_date AS startDate,end_date AS endDate,enrollment_start AS enrollmentStart,enrollment_end AS enrollmentEnd,seats,requirements,details,status,enrollment_url AS enrollmentUrl,enrollment_open AS enrollmentOpen,updated_at AS updatedAt FROM courses WHERE year=? AND status IN ('published','cancelled') ORDER BY start_date").bind(year).all();return json({courses:rows.results||[]},200,cors)}
 if(!user)return json({error:'Autenticação necessária'},401,cors);const isManager=authorize(user,['gerente','admin']);
 if(p==='/api/courses/manage'&&request.method==='GET'&&isManager){await rateLimit(request,env,user,'courses-read');const rows=await env.DB.prepare('SELECT * FROM courses ORDER BY year DESC,start_date').all();return json({courses:rows.results||[]},200,cors)}
 if(p==='/api/courses'&&request.method==='POST'&&isManager){await rateLimit(request,env,user,'courses-write');const raw=await parse(request),year=Number(raw.year),title=text(raw.title,240),status=statuses.has(raw.status)?raw.status:'draft',url=text(raw.enrollmentUrl,1000);if(!title||year<2020||year>2100)return json({error:'Título/ano inválidos'},400,cors);if(url&&!/^https:\/\/docs\.google\.com\/forms\//i.test(url))return json({error:'URL de inscrição não autorizada'},400,cors);const cid=/^[a-zA-Z0-9_-]{1,100}$/.test(String(raw.id||''))?String(raw.id):id(),now=new Date().toISOString(),seats=raw.seats?Math.max(1,Math.min(10000,Number(raw.seats))):null;await env.DB.prepare('INSERT OR REPLACE INTO courses(id,year,title,audience,location,start_date,end_date,enrollment_start,enrollment_end,seats,requirements,details,status,enrollment_url,enrollment_open,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(cid,year,title,text(raw.audience,500),text(raw.location,500),date(raw.startDate),date(raw.endDate),date(raw.enrollmentStart),date(raw.enrollmentEnd),seats,text(raw.requirements,4000),text(raw.details,8000),status,url,raw.enrollmentOpen===true?1:0,now).run();await audit(env.DB,user,'course.saved','course',cid);return json({ok:true,id:cid},200,cors)}
 if(p==='/api/enrollments'&&request.method==='GET'&&isManager){await rateLimit(request,env,user,'enrollments-read');const rows=await env.DB.prepare('SELECT * FROM enrollments ORDER BY created_at DESC LIMIT 500').all();return json({enrollments:rows.results||[]},200,cors)}
 if(p==='/api/enrollments/status'&&request.method==='POST'&&isManager){await rateLimit(request,env,user,'enrollments-write');const x=await parse(request),allowed=['received','under-review','approved','not-approved','cancelled'];if(!/^[a-zA-Z0-9_-]{1,100}$/.test(String(x.id||''))||!allowed.includes(x.status))return json({error:'Situação inválida'},400,cors);await env.DB.prepare('UPDATE enrollments SET status=?,updated_at=? WHERE id=?').bind(x.status,new Date().toISOString(),x.id).run();await audit(env.DB,user,'enrollment.status','enrollment',x.id);return json({ok:true},200,cors)}
 if(p==='/api/audit'&&request.method==='GET'&&isManager){await rateLimit(request,env,user,'audit-read');const rows=await env.DB.prepare('SELECT * FROM audit_log ORDER BY id DESC LIMIT 200').all();return json({events:rows.results||[]},200,cors)}return json({error:'Não encontrado ou sem permissão'},404,cors)}catch(err){return json({error:err?.status===429?'Limite de requisições atingido':'Requisição rejeitada'},err?.status||400,cors)}}
