const SAFE_METHODS=new Set(['GET','HEAD','OPTIONS']);
export const securityHeaders={
 'X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'no-referrer',
 'Permissions-Policy':'camera=(), geolocation=(), payment=(), usb=()',
 'Cross-Origin-Resource-Policy':'same-site','Cache-Control':'no-store'
};
export function cors(origin,env){const allowed=(env.ALLOWED_ORIGINS||'').split(',').map(x=>x.trim()).filter(Boolean);if(!origin||!allowed.includes(origin))return null;return {...securityHeaders,'Access-Control-Allow-Origin':origin,'Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization, X-Turnstile-Token','Access-Control-Max-Age':'600','Vary':'Origin'}}
export function assertJson(request,max=30000){const type=request.headers.get('content-type')||'';const len=Number(request.headers.get('content-length')||0);if(!type.toLowerCase().startsWith('application/json'))throw Object.assign(Error('json-required'),{status:415});if(len>max)throw Object.assign(Error('too-large'),{status:413})}
export async function verifyTurnstile(request,env,required=false){if(!required&&!env.TURNSTILE_SECRET)return true;if(!env.TURNSTILE_SECRET)throw Object.assign(Error('bot-protection-unconfigured'),{status:503});const token=request.headers.get('X-Turnstile-Token')||'';if(!token)throw Object.assign(Error('bot-check-required'),{status:403});const form=new FormData();form.set('secret',env.TURNSTILE_SECRET);form.set('response',token);const ip=request.headers.get('CF-Connecting-IP');if(ip)form.set('remoteip',ip);const r=await fetch('https://challenges.cloudflare.com/turnstile/v0/siteverify',{method:'POST',body:form,signal:AbortSignal.timeout(7000)});const result=await r.json().catch(()=>({success:false}));if(!r.ok||result.success!==true)throw Object.assign(Error('bot-check-failed'),{status:403});return true}
export async function rateLimit(request,env,identity,prefix='api'){if(!env.RATE_LIMITER)throw Object.assign(Error('rate-limit-unconfigured'),{status:503});const ip=request.headers.get('CF-Connecting-IP')||'unknown',subject=identity?.subject||'anonymous',key=`${prefix}:${subject}:${ip}`;const result=await env.RATE_LIMITER.limit({key});if(!result.success)throw Object.assign(Error('rate-limit'),{status:429});return true}
export function rejectUnsafeQuery(request){const u=new URL(request.url);if(!SAFE_METHODS.has(request.method)&&u.searchParams.size)throw Object.assign(Error('unsafe-query'),{status:400})}
